name = "ProtoStructs"
uuid = "437b6fc4-8e8e-11e9-3fa1-ad391e66c018"
authors = ["Simon Christ"]
version = "1.2.0"

[compat]
REPL = "1.11.0"
julia = "1.6"

[extras]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "REPL"]
